[package]
name = "dircast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
aws-creds = "0.30.0"
rust-s3 = "0.32.3"
tokio = { version = "1", features = ["full"] }
